
spring:
  datasource:
    url: jdbc:mysql://prototypedb:3306/demo
    username: dbuser
    password: dbp4ss
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
  data.jpa.repositories.enabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
server.port: 42444
